name: Build/lint/test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Git-Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Initial node modules
        run: npm i
      - name: Biuld production bundle
        run: npm run build:prod
      - name: Lint ts
        if: always()
        run: npm run lint:ts
      - name: Lint css
        if: always()
        run: npm run lint:css
      - name: Test unit
        if: always()
        run: npm run test:unit
      - name: Build storybook
        if: always()
        run: npm run storybook:build
      - name: Test screenshot
        if: always()
        run: npm run test:ui:ci
     